// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://biqdopknsjihuyhiybwa.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJpcWRvcGtuc2ppaHV5aGl5YndhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTEyNTM5MTksImV4cCI6MjA2NjgyOTkxOX0.DyBcSc_fNZH4QYUGoLxFdrCYLEvP6auwx2W1rcSp0-Q";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});